// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnqueueRequest {
    /// Function identifier (e.g., "send-email")
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Serialized function arguments (JSON)
    #[prost(bytes = "vec", tag = "2")]
    pub args: ::prost::alloc::vec::Vec<u8>,
    /// Retry and backoff configuration
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<JobOptions>,
    /// Optional: prevent duplicate jobs
    #[prost(string, tag = "4")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnqueueResponse {
    /// Unique job identifier (UUID)
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// True if job already existed (idempotency)
    #[prost(bool, tag = "2")]
    pub deduplicated: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobOptions {
    /// Maximum retry attempts (default: 3)
    #[prost(int32, tag = "1")]
    pub max_attempts: i32,
    /// "fixed", "exponential", "linear"
    #[prost(string, tag = "2")]
    pub backoff: ::prost::alloc::string::String,
    /// Initial delay between retries (default: 1000)
    #[prost(int32, tag = "3")]
    pub initial_delay_ms: i32,
    /// Maximum delay cap (default: 60000)
    #[prost(int32, tag = "4")]
    pub max_delay_ms: i32,
    /// Per-attempt timeout (default: 30000)
    #[prost(int32, tag = "5")]
    pub timeout_ms: i32,
    /// Randomization factor 0.0-1.0 (default: 0.1)
    #[prost(float, tag = "6")]
    pub jitter: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PollRequest {
    /// Unique worker identifier
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    /// Function names this worker can handle (empty = all)
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// How many jobs this worker can handle at once
    #[prost(int32, tag = "3")]
    pub concurrency: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Job {
    /// Job UUID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Function identifier
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Serialized arguments
    #[prost(bytes = "vec", tag = "3")]
    pub args: ::prost::alloc::vec::Vec<u8>,
    /// Current attempt number (1-indexed)
    #[prost(int32, tag = "4")]
    pub attempt: i32,
    /// Unix timestamp when job times out
    #[prost(int64, tag = "5")]
    pub deadline_ms: i64,
    /// Current job status
    #[prost(enumeration = "JobStatus", tag = "6")]
    pub status: i32,
    /// Last error message (if failed)
    #[prost(string, tag = "7")]
    pub error: ::prost::alloc::string::String,
    /// Serialized result (if success)
    #[prost(bytes = "vec", tag = "8")]
    pub result: ::prost::alloc::vec::Vec<u8>,
    /// Unix timestamp (ms) of creation
    #[prost(int64, tag = "9")]
    pub created_at: i64,
    /// Unix timestamp (ms) of next scheduled run
    #[prost(int64, tag = "10")]
    pub scheduled_at: i64,
    /// Unix timestamp (ms) when job started (0 if not started)
    #[prost(int64, tag = "11")]
    pub started_at: i64,
    /// Unix timestamp (ms) when job completed (0 if not completed)
    #[prost(int64, tag = "12")]
    pub completed_at: i64,
    /// Maximum retry attempts
    #[prost(int32, tag = "13")]
    pub max_attempts: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckRequest {
    /// Job to acknowledge
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// Execution result
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<AckResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckResult {
    /// True if execution succeeded
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Serialized return value (if success)
    #[prost(bytes = "vec", tag = "2")]
    pub return_value: ::prost::alloc::vec::Vec<u8>,
    /// Error message (if failed)
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
    /// SDK can force no-retry on certain errors
    #[prost(bool, tag = "4")]
    pub should_retry: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AckResponse {
    /// Job's new status after ack
    #[prost(enumeration = "JobStatus", tag = "1")]
    pub new_status: i32,
    /// Next attempt number (if retrying)
    #[prost(int32, tag = "2")]
    pub next_attempt: i32,
    /// Next scheduled run (if retrying)
    #[prost(int64, tag = "3")]
    pub next_run_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJobRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelResponse {
    /// True if job was cancelled
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Error message if cancellation failed
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetryRequest {
    /// Job to retry
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetryResponse {
    /// True if job was reset to pending
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Error message if retry failed
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJobsRequest {
    /// Filter by status (empty = all)
    #[prost(enumeration = "JobStatus", repeated, tag = "1")]
    pub statuses: ::prost::alloc::vec::Vec<i32>,
    /// Filter by function name (empty = all)
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Max results (default: 100)
    #[prost(int32, tag = "3")]
    pub limit: i32,
    /// Pagination offset
    #[prost(int32, tag = "4")]
    pub offset: i32,
    /// "created_at", "scheduled_at" (default: created_at)
    #[prost(string, tag = "5")]
    pub order_by: ::prost::alloc::string::String,
    /// Sort order (default: false = descending)
    #[prost(bool, tag = "6")]
    pub ascending: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJobsResponse {
    #[prost(message, repeated, tag = "1")]
    pub jobs: ::prost::alloc::vec::Vec<Job>,
    /// Total matching jobs (for pagination)
    #[prost(int32, tag = "2")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeRequest {
    /// Job IDs to subscribe to
    #[prost(string, repeated, tag = "1")]
    pub job_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// True to unsubscribe from these IDs
    #[prost(bool, tag = "2")]
    pub unsubscribe: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobCompletion {
    /// Completed job ID
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// Final status (success, dead, cancelled)
    #[prost(enumeration = "JobStatus", tag = "2")]
    pub status: i32,
    /// Serialized result (if success)
    #[prost(bytes = "vec", tag = "3")]
    pub result: ::prost::alloc::vec::Vec<u8>,
    /// Error message (if dead/failed)
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Schedule {
    /// Schedule UUID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Unique function namespace
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Cron expression (e.g., "0 8 * * *")
    #[prost(string, tag = "3")]
    pub cron_expression: ::prost::alloc::string::String,
    /// IANA timezone (default: "UTC")
    #[prost(string, tag = "4")]
    pub timezone: ::prost::alloc::string::String,
    /// Current status
    #[prost(enumeration = "ScheduleStatus", tag = "5")]
    pub status: i32,
    /// Next trigger time (Unix ms)
    #[prost(int64, tag = "6")]
    pub next_run_at: i64,
    /// Last trigger time (Unix ms, 0 if never)
    #[prost(int64, tag = "7")]
    pub last_run_at: i64,
    /// Creation timestamp (Unix ms)
    #[prost(int64, tag = "8")]
    pub created_at: i64,
    /// Last update timestamp (Unix ms)
    #[prost(int64, tag = "9")]
    pub updated_at: i64,
    /// Options applied to triggered jobs
    #[prost(message, optional, tag = "10")]
    pub handler_options: ::core::option::Option<JobOptions>,
    /// Serialized function arguments (JSON)
    #[prost(bytes = "vec", tag = "11")]
    pub args: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateScheduleRequest {
    /// Unique function namespace
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Cron expression
    #[prost(string, tag = "2")]
    pub cron_expression: ::prost::alloc::string::String,
    /// IANA timezone (default: "UTC")
    #[prost(string, tag = "3")]
    pub timezone: ::prost::alloc::string::String,
    /// Options applied to triggered jobs
    #[prost(message, optional, tag = "4")]
    pub handler_options: ::core::option::Option<JobOptions>,
    /// Serialized function arguments (JSON)
    #[prost(bytes = "vec", tag = "5")]
    pub args: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScheduleRequest {
    /// Schedule ID or name
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSchedulesRequest {
    /// "active", "paused", or "all" (default: all except deleted)
    #[prost(string, tag = "1")]
    pub status_filter: ::prost::alloc::string::String,
    /// Max results (default: 100)
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// Pagination offset
    #[prost(int32, tag = "3")]
    pub offset: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSchedulesResponse {
    #[prost(message, repeated, tag = "1")]
    pub schedules: ::prost::alloc::vec::Vec<Schedule>,
    /// Total matching schedules
    #[prost(int32, tag = "2")]
    pub total: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateScheduleRequest {
    /// Schedule to update
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    /// New cron expression (optional)
    #[prost(string, tag = "2")]
    pub cron_expression: ::prost::alloc::string::String,
    /// New timezone (optional)
    #[prost(string, tag = "3")]
    pub timezone: ::prost::alloc::string::String,
    /// New options (optional)
    #[prost(message, optional, tag = "4")]
    pub handler_options: ::core::option::Option<JobOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PauseScheduleRequest {
    /// Schedule to pause
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResumeScheduleRequest {
    /// Schedule to resume
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteScheduleRequest {
    /// Schedule to delete
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteScheduleResponse {
    /// True if schedule was deleted
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Error message if deletion failed
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobStatus {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Success = 3,
    Failed = 4,
    Dead = 5,
    Cancelled = 6,
}
impl JobStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOB_STATUS_UNSPECIFIED",
            Self::Pending => "JOB_STATUS_PENDING",
            Self::Running => "JOB_STATUS_RUNNING",
            Self::Success => "JOB_STATUS_SUCCESS",
            Self::Failed => "JOB_STATUS_FAILED",
            Self::Dead => "JOB_STATUS_DEAD",
            Self::Cancelled => "JOB_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "JOB_STATUS_PENDING" => Some(Self::Pending),
            "JOB_STATUS_RUNNING" => Some(Self::Running),
            "JOB_STATUS_SUCCESS" => Some(Self::Success),
            "JOB_STATUS_FAILED" => Some(Self::Failed),
            "JOB_STATUS_DEAD" => Some(Self::Dead),
            "JOB_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ScheduleStatus {
    Unspecified = 0,
    Active = 1,
    Paused = 2,
    Deleted = 3,
}
impl ScheduleStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SCHEDULE_STATUS_UNSPECIFIED",
            Self::Active => "SCHEDULE_STATUS_ACTIVE",
            Self::Paused => "SCHEDULE_STATUS_PAUSED",
            Self::Deleted => "SCHEDULE_STATUS_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCHEDULE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "SCHEDULE_STATUS_ACTIVE" => Some(Self::Active),
            "SCHEDULE_STATUS_PAUSED" => Some(Self::Paused),
            "SCHEDULE_STATUS_DELETED" => Some(Self::Deleted),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod reseolio_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// The Reseolio service provides durable function execution
    #[derive(Debug, Clone)]
    pub struct ReseolioClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ReseolioClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ReseolioClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ReseolioClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ReseolioClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Enqueue a new job for durable execution
        pub async fn enqueue_job(
            &mut self,
            request: impl tonic::IntoRequest<super::EnqueueRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnqueueResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/EnqueueJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "EnqueueJob"));
            self.inner.unary(req, path, codec).await
        }
        /// Worker polls for available jobs (bidirectional streaming)
        pub async fn poll_jobs(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::PollRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Job>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/PollJobs",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "PollJobs"));
            self.inner.streaming(req, path, codec).await
        }
        /// Report job completion (success or failure)
        pub async fn ack_job(
            &mut self,
            request: impl tonic::IntoRequest<super::AckRequest>,
        ) -> std::result::Result<tonic::Response<super::AckResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/reseolio.Reseolio/AckJob");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("reseolio.Reseolio", "AckJob"));
            self.inner.unary(req, path, codec).await
        }
        /// Query the status of a specific job
        pub async fn get_job(
            &mut self,
            request: impl tonic::IntoRequest<super::GetJobRequest>,
        ) -> std::result::Result<tonic::Response<super::Job>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/reseolio.Reseolio/GetJob");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("reseolio.Reseolio", "GetJob"));
            self.inner.unary(req, path, codec).await
        }
        /// Cancel a pending job
        pub async fn cancel_job(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/CancelJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "CancelJob"));
            self.inner.unary(req, path, codec).await
        }
        /// Retry a dead/failed job (resets to PENDING with attempt=0)
        pub async fn retry_job(
            &mut self,
            request: impl tonic::IntoRequest<super::RetryRequest>,
        ) -> std::result::Result<tonic::Response<super::RetryResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/RetryJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "RetryJob"));
            self.inner.unary(req, path, codec).await
        }
        /// List jobs with filtering
        pub async fn list_jobs(
            &mut self,
            request: impl tonic::IntoRequest<super::ListJobsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListJobsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/ListJobs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "ListJobs"));
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to job completion events (push-based, no polling)
        pub async fn subscribe_to_jobs(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::SubscribeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::JobCompletion>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/SubscribeToJobs",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "SubscribeToJobs"));
            self.inner.streaming(req, path, codec).await
        }
        /// Create a new cron schedule
        pub async fn create_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateScheduleRequest>,
        ) -> std::result::Result<tonic::Response<super::Schedule>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/CreateSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "CreateSchedule"));
            self.inner.unary(req, path, codec).await
        }
        /// Get a schedule by ID
        pub async fn get_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::GetScheduleRequest>,
        ) -> std::result::Result<tonic::Response<super::Schedule>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/GetSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "GetSchedule"));
            self.inner.unary(req, path, codec).await
        }
        /// List schedules with filtering
        pub async fn list_schedules(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSchedulesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSchedulesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/ListSchedules",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "ListSchedules"));
            self.inner.unary(req, path, codec).await
        }
        /// Update a schedule's cron expression, timezone, or options
        pub async fn update_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateScheduleRequest>,
        ) -> std::result::Result<tonic::Response<super::Schedule>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/UpdateSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "UpdateSchedule"));
            self.inner.unary(req, path, codec).await
        }
        /// Pause a schedule (stop triggering)
        pub async fn pause_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseScheduleRequest>,
        ) -> std::result::Result<tonic::Response<super::Schedule>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/PauseSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "PauseSchedule"));
            self.inner.unary(req, path, codec).await
        }
        /// Resume a paused schedule
        pub async fn resume_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::ResumeScheduleRequest>,
        ) -> std::result::Result<tonic::Response<super::Schedule>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/ResumeSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "ResumeSchedule"));
            self.inner.unary(req, path, codec).await
        }
        /// Delete a schedule (soft delete)
        pub async fn delete_schedule(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteScheduleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/DeleteSchedule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "DeleteSchedule"));
            self.inner.unary(req, path, codec).await
        }
    }
}
