// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnqueueRequest {
    /// Function identifier (e.g., "send-email")
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Serialized function arguments (JSON)
    #[prost(bytes = "vec", tag = "2")]
    pub args: ::prost::alloc::vec::Vec<u8>,
    /// Retry and backoff configuration
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<JobOptions>,
    /// Optional: prevent duplicate jobs
    #[prost(string, tag = "4")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnqueueResponse {
    /// Unique job identifier (UUID)
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// True if job already existed (idempotency)
    #[prost(bool, tag = "2")]
    pub deduplicated: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobOptions {
    /// Maximum retry attempts (default: 3)
    #[prost(int32, tag = "1")]
    pub max_attempts: i32,
    /// "fixed", "exponential", "linear"
    #[prost(string, tag = "2")]
    pub backoff: ::prost::alloc::string::String,
    /// Initial delay between retries (default: 1000)
    #[prost(int32, tag = "3")]
    pub initial_delay_ms: i32,
    /// Maximum delay cap (default: 60000)
    #[prost(int32, tag = "4")]
    pub max_delay_ms: i32,
    /// Per-attempt timeout (default: 30000)
    #[prost(int32, tag = "5")]
    pub timeout_ms: i32,
    /// Randomization factor 0.0-1.0 (default: 0.1)
    #[prost(float, tag = "6")]
    pub jitter: f32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PollRequest {
    /// Unique worker identifier
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    /// Function names this worker can handle (empty = all)
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// How many jobs this worker can handle at once
    #[prost(int32, tag = "3")]
    pub concurrency: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Job {
    /// Job UUID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Function identifier
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Serialized arguments
    #[prost(bytes = "vec", tag = "3")]
    pub args: ::prost::alloc::vec::Vec<u8>,
    /// Current attempt number (1-indexed)
    #[prost(int32, tag = "4")]
    pub attempt: i32,
    /// Unix timestamp when job times out
    #[prost(int64, tag = "5")]
    pub deadline_ms: i64,
    /// Current job status
    #[prost(enumeration = "JobStatus", tag = "6")]
    pub status: i32,
    /// Last error message (if failed)
    #[prost(string, tag = "7")]
    pub error: ::prost::alloc::string::String,
    /// Serialized result (if success)
    #[prost(bytes = "vec", tag = "8")]
    pub result: ::prost::alloc::vec::Vec<u8>,
    /// Unix timestamp of creation
    #[prost(int64, tag = "9")]
    pub created_at: i64,
    /// Unix timestamp of next scheduled run
    #[prost(int64, tag = "10")]
    pub scheduled_at: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckRequest {
    /// Job to acknowledge
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// Execution result
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<AckResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckResult {
    /// True if execution succeeded
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Serialized return value (if success)
    #[prost(bytes = "vec", tag = "2")]
    pub return_value: ::prost::alloc::vec::Vec<u8>,
    /// Error message (if failed)
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
    /// SDK can force no-retry on certain errors
    #[prost(bool, tag = "4")]
    pub should_retry: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckResponse {
    /// Job's new status after ack
    #[prost(enumeration = "JobStatus", tag = "1")]
    pub new_status: i32,
    /// Next attempt number (if retrying)
    #[prost(int32, tag = "2")]
    pub next_attempt: i32,
    /// Next scheduled run (if retrying)
    #[prost(int64, tag = "3")]
    pub next_run_at: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJobRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelResponse {
    /// True if job was cancelled
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Error message if cancellation failed
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJobsRequest {
    /// Filter by status (empty = all)
    #[prost(enumeration = "JobStatus", repeated, tag = "1")]
    pub statuses: ::prost::alloc::vec::Vec<i32>,
    /// Filter by function name (empty = all)
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Max results (default: 100)
    #[prost(int32, tag = "3")]
    pub limit: i32,
    /// Pagination offset
    #[prost(int32, tag = "4")]
    pub offset: i32,
    /// "created_at", "scheduled_at" (default: created_at)
    #[prost(string, tag = "5")]
    pub order_by: ::prost::alloc::string::String,
    /// Sort order (default: false = descending)
    #[prost(bool, tag = "6")]
    pub ascending: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJobsResponse {
    #[prost(message, repeated, tag = "1")]
    pub jobs: ::prost::alloc::vec::Vec<Job>,
    /// Total matching jobs (for pagination)
    #[prost(int32, tag = "2")]
    pub total: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobStatus {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Success = 3,
    Failed = 4,
    Dead = 5,
    Cancelled = 6,
}
impl JobStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            JobStatus::Unspecified => "JOB_STATUS_UNSPECIFIED",
            JobStatus::Pending => "JOB_STATUS_PENDING",
            JobStatus::Running => "JOB_STATUS_RUNNING",
            JobStatus::Success => "JOB_STATUS_SUCCESS",
            JobStatus::Failed => "JOB_STATUS_FAILED",
            JobStatus::Dead => "JOB_STATUS_DEAD",
            JobStatus::Cancelled => "JOB_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "JOB_STATUS_PENDING" => Some(Self::Pending),
            "JOB_STATUS_RUNNING" => Some(Self::Running),
            "JOB_STATUS_SUCCESS" => Some(Self::Success),
            "JOB_STATUS_FAILED" => Some(Self::Failed),
            "JOB_STATUS_DEAD" => Some(Self::Dead),
            "JOB_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod reseolio_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// The Reseolio service provides durable function execution
    #[derive(Debug, Clone)]
    pub struct ReseolioClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ReseolioClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ReseolioClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ReseolioClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ReseolioClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Enqueue a new job for durable execution
        pub async fn enqueue_job(
            &mut self,
            request: impl tonic::IntoRequest<super::EnqueueRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnqueueResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/EnqueueJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "EnqueueJob"));
            self.inner.unary(req, path, codec).await
        }
        /// Worker polls for available jobs (bidirectional streaming)
        pub async fn poll_jobs(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::PollRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Job>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/PollJobs",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "PollJobs"));
            self.inner.streaming(req, path, codec).await
        }
        /// Report job completion (success or failure)
        pub async fn ack_job(
            &mut self,
            request: impl tonic::IntoRequest<super::AckRequest>,
        ) -> std::result::Result<tonic::Response<super::AckResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/reseolio.Reseolio/AckJob");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("reseolio.Reseolio", "AckJob"));
            self.inner.unary(req, path, codec).await
        }
        /// Query the status of a specific job
        pub async fn get_job(
            &mut self,
            request: impl tonic::IntoRequest<super::GetJobRequest>,
        ) -> std::result::Result<tonic::Response<super::Job>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/reseolio.Reseolio/GetJob");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("reseolio.Reseolio", "GetJob"));
            self.inner.unary(req, path, codec).await
        }
        /// Cancel a pending job
        pub async fn cancel_job(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/CancelJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "CancelJob"));
            self.inner.unary(req, path, codec).await
        }
        /// List jobs with filtering
        pub async fn list_jobs(
            &mut self,
            request: impl tonic::IntoRequest<super::ListJobsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListJobsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/reseolio.Reseolio/ListJobs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("reseolio.Reseolio", "ListJobs"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod reseolio_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ReseolioServer.
    #[async_trait]
    pub trait Reseolio: Send + Sync + 'static {
        /// Enqueue a new job for durable execution
        async fn enqueue_job(
            &self,
            request: tonic::Request<super::EnqueueRequest>,
        ) -> std::result::Result<tonic::Response<super::EnqueueResponse>, tonic::Status>;
        /// Server streaming response type for the PollJobs method.
        type PollJobsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Job, tonic::Status>,
            >
            + Send
            + 'static;
        /// Worker polls for available jobs (bidirectional streaming)
        async fn poll_jobs(
            &self,
            request: tonic::Request<tonic::Streaming<super::PollRequest>>,
        ) -> std::result::Result<tonic::Response<Self::PollJobsStream>, tonic::Status>;
        /// Report job completion (success or failure)
        async fn ack_job(
            &self,
            request: tonic::Request<super::AckRequest>,
        ) -> std::result::Result<tonic::Response<super::AckResponse>, tonic::Status>;
        /// Query the status of a specific job
        async fn get_job(
            &self,
            request: tonic::Request<super::GetJobRequest>,
        ) -> std::result::Result<tonic::Response<super::Job>, tonic::Status>;
        /// Cancel a pending job
        async fn cancel_job(
            &self,
            request: tonic::Request<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status>;
        /// List jobs with filtering
        async fn list_jobs(
            &self,
            request: tonic::Request<super::ListJobsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListJobsResponse>,
            tonic::Status,
        >;
    }
    /// The Reseolio service provides durable function execution
    #[derive(Debug)]
    pub struct ReseolioServer<T: Reseolio> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: Reseolio> ReseolioServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ReseolioServer<T>
    where
        T: Reseolio,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/reseolio.Reseolio/EnqueueJob" => {
                    #[allow(non_camel_case_types)]
                    struct EnqueueJobSvc<T: Reseolio>(pub Arc<T>);
                    impl<T: Reseolio> tonic::server::UnaryService<super::EnqueueRequest>
                    for EnqueueJobSvc<T> {
                        type Response = super::EnqueueResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EnqueueRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Reseolio>::enqueue_job(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = EnqueueJobSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/reseolio.Reseolio/PollJobs" => {
                    #[allow(non_camel_case_types)]
                    struct PollJobsSvc<T: Reseolio>(pub Arc<T>);
                    impl<T: Reseolio> tonic::server::StreamingService<super::PollRequest>
                    for PollJobsSvc<T> {
                        type Response = super::Job;
                        type ResponseStream = T::PollJobsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::PollRequest>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Reseolio>::poll_jobs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PollJobsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/reseolio.Reseolio/AckJob" => {
                    #[allow(non_camel_case_types)]
                    struct AckJobSvc<T: Reseolio>(pub Arc<T>);
                    impl<T: Reseolio> tonic::server::UnaryService<super::AckRequest>
                    for AckJobSvc<T> {
                        type Response = super::AckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Reseolio>::ack_job(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = AckJobSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/reseolio.Reseolio/GetJob" => {
                    #[allow(non_camel_case_types)]
                    struct GetJobSvc<T: Reseolio>(pub Arc<T>);
                    impl<T: Reseolio> tonic::server::UnaryService<super::GetJobRequest>
                    for GetJobSvc<T> {
                        type Response = super::Job;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetJobRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Reseolio>::get_job(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetJobSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/reseolio.Reseolio/CancelJob" => {
                    #[allow(non_camel_case_types)]
                    struct CancelJobSvc<T: Reseolio>(pub Arc<T>);
                    impl<T: Reseolio> tonic::server::UnaryService<super::CancelRequest>
                    for CancelJobSvc<T> {
                        type Response = super::CancelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Reseolio>::cancel_job(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CancelJobSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/reseolio.Reseolio/ListJobs" => {
                    #[allow(non_camel_case_types)]
                    struct ListJobsSvc<T: Reseolio>(pub Arc<T>);
                    impl<T: Reseolio> tonic::server::UnaryService<super::ListJobsRequest>
                    for ListJobsSvc<T> {
                        type Response = super::ListJobsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListJobsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Reseolio>::list_jobs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ListJobsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: Reseolio> Clone for ReseolioServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: Reseolio> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: Reseolio> tonic::server::NamedService for ReseolioServer<T> {
        const NAME: &'static str = "reseolio.Reseolio";
    }
}
